### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by EvgenijM86** [GTNewHorizons/GT5-Unofficial#105]
I am new to minecraft modding development. I tried ./gradlew build on linux, but it eventually failed with a bunch of errors like this:

```
Could not GET 'http://addons-origin.cursecdn.com/files/2246/918/CoFHLib-%5B1.7.10%5D1.0.3-175-dev.xml'. Received status code 403 from server: Forbidden
Could not GET 'http://addons-origin.cursecdn.com/files/2246/918/CoFHCore-%5B1.7.10%5D3.0.3-303-dev.xml'. Received status code 403 from server: Forbidden
Could not GET 'http://addons-origin.cursecdn.com/files/2246/918/Railcraft-1.7.10-9.12.2.0.xml'. Received status code 403 from server: Forbidden
```

More Info:
```
GT5-Unofficial$ ./gradlew --version
------------------------------------------------------------
Gradle 2.0
------------------------------------------------------------

Build time:   2014-07-01 07:45:34 UTC
Build number: none
Revision:     b6ead6fa452dfdadec484059191eb641d817226c

Groovy:       2.3.3
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.11.8-041108-generic amd64
```

**Comment by EvgenijM86** [comment]
I also tried redownloading repo and doing:
./gradlew SetupDecompWorkspace
./gradlew build

I get same errors.

**Comment by bartimaeusnek** [comment]
well get these libs (CoFHLib.1.7.10-1.0.3-175-dev, CoFHCore1.7.10-3.0.3-303-dev,Railcraft-1.7.10-9.12.2.0) as jars and put them in *yourBuildingDir*/libs

**Comment by bartimaeusnek** [comment]
funny i just build it without adding anything manual and it worked, so i can close this?

**Comment by EvgenijM86** [comment]
I guess. It probably worked because gradle caches things inside ~/.gradle directory (or some similar directory on windows), so you already had everything that was needed to build it.

**Comment by EvgenijM86** [comment]
If you visit those links in a browser:
http://addons-origin.cursecdn.com/files/2246/918/Railcraft-1.7.10-9.12.2.0.xml
You will find that they are forbidden. So, someone who does not have a gradle cache of those files will probably have to do things manually like I did.

**Comment by Dream-Master** [comment]
@EvgenijM86 use us link
http://downloads.gtnewhorizons.com/#Mods_for_Jenkins
open it up when it not work.
