### ISSUE TITLE
GT wireless redstone covers cannot be placed on some casing blocks

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT5-Unofficial#166]
@subj
E.g. inert chemical reactor casings, turbine casings, EBF casings.
It makes it hard to use e.g. "need maintenance" cover with multiblocks, and some uses of machine controller are also limited

**Comment by Dream-Master** [comment]
@repo-alt is this some gt++ device/casing ?

**Comment by repo-alt** [comment]
No, pretty regular GT5 casings

**Comment by repo-alt** [comment]
Related issue: https://github.com/GTNewHorizons/NewHorizons/issues/3363
Some multiblocks like Combustion engine or Turbine require special casings all around the controller, so if these casings don't accept covers, one cannot get "need maintenance" signal from the controller.

**Comment by Technus** [comment]
Needs maintenance on controller+strong signal setting and reading adjacent block?

**Comment by repo-alt** [comment]
I can switch to strong signal? Now that's a surprise. Can I switch e.g. fluid level emitter to strong signal too?

**Comment by draknyte1** [comment]
Covers can only be placed on tile entities. Casings are just normal blocks..

**Comment by repo-alt** [comment]
I see. Well, it would be nice to have strong signal support in all redstone emitting covers then (if they don't have it - I'll check some of them later today).

**Comment by repo-alt** [comment]
@Technus I was unable to find any indications of strong redstone mode either in GT_Cover_NeedMaintainance.java or in the MetaTileEntity code it uses. Definitely nothing like that can be switched with a screwdriver.

**Comment by repo-alt** [comment]
What I was able to use is that I noticed that the cover sets redstone signal to the opposite side of the controller, and there it can be read by the wireless redstone transmitter (in) cover .

**Comment by leagris** [comment]
Use a charged soldering iron with thin soldering wire in hotbar to switch to strong signal

**Comment by repo-alt** [comment]
Thanks! This is very useful information. I think this issue may be closed, since both the original question was 
 answered (covers may be placed only on tilentities) and a workaround is provided (strong signal output).

**Comment by richardhendricks** [comment]
will add quest to explain.

**Comment by richardhendricks** [comment]
Added MV quest for needs maintenance cover that explains using strong redstone signals

![image](https://user-images.githubusercontent.com/1214811/57189242-98a9dd00-6ed1-11e9-946a-7d5aa5a533c2.png)
