### ISSUE TITLE
Primitive Blast Funace does not re-check open sky when inactive

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT5-Unofficial#240]
When the Primitive Blast Furnace becomes inactive because sky is obstructed: it does not return to its active state when obstruction is removed.

Even soft hammering the controller does not cause a re-check.

[Gregtech 5.09.33.31 build 395](http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/lastSuccessfulBuild/artifact/build/libs/gregtech-5.09.33.31.jar)

**Comment by richardhendricks** [comment]
Since when did it need to see sky? Or is this not the Bricked Blast Furnace?

**Comment by leagris** [comment]
> Since when did it need to see sky? Or is this not the Bricked Blast Furnace?

@richardhendricks The Bricked Blast Furnace and the Bronze Blast Furnace are both the Primitive Blast Furnace internally in Gregtech.

**Comment by richardhendricks** [comment]
Oh do you mean the block above the opening is solid or do you mean literally cannot see sky like a solar panel? 

I have placed many underground just fine.

**Comment by richardhendricks** [comment]
Also I prefer we keep all tickets under NewHorizons project instead of scattering in each project. Makes it easier to track that way.

**Comment by Dream-Master** [comment]
@leagris yes can you open up th issue on the Modpack main repo?
Thanks
