### ISSUE TITLE
FakePlayers does not provide owner's uuid

### ISSUE THREAD

**Issue by Relvl** [GTNewHorizons/GT5-Unofficial#244]
Block breaking machines (ex. Pumps, Miners) does not provide owner player's UUID.
Ex: gregtech.api.util.GT_Utility#eraseBlockByFakePlayer

Few server plugins (ex. GriefPrevention) check permissions to build/break blocks with uuid checking.
https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java

Please provide correct uuid.

**Comment by Relvl** [comment]
Pull Request sended, close issue
https://github.com/GTNewHorizons/GT5-Unofficial/pull/246

**Comment by richardhendricks** [comment]
Our procedure has us mark "finished" ticket as "fixed in dev" and closed once we release a change log with a new release.

**Comment by richardhendricks** [comment]
Needs to be tested
- [ ] What happens with pigmen in the nether?  Currently they "attack" the miner and ignore a player. If this changes that behavior, that won't work.
- [ ] What will happen if a player tries to teleport on the official servers? Does this prevent that?

**Comment by Dream-Master** [comment]
merged

**Comment by GTNH-Colen** [comment]
Honestly is this a huge issue? I've got ~100 days playtime on ETA and not seen a single player ever complain about being griefed, if we can implement this without disrupting other vital plugins then sure i'm all for it but if it means hurting teleports then absolutely not.

If a player is somehow griefed by some insanely complicated rude goldberg machine using block breakers and what some kind of frame mover to go with it I guess? Then surely we can just rollback the chunks? If it's a trade off between 1 grief every 200 days and hurting every players ability to teleport on a daily basis then I know what i'd choose.

The teleport plugins are broken as it is when mining drills are running, do we really want to exacerbate this issue? See https://github.com/GTNewHorizons/NewHorizons/issues/5004

**Comment by Relvl** [comment]
I don’t understand English very well, but as far as I understand, miner operations interfere with teleporting? Maybe in this case, it’s better to fix the teleportation plugin? As my experience tells me, this is a better decision than banning or breaking a miner.

**Comment by Relvl** [comment]
> Needs to be tested
> 
> * [ ]  What happens with pigmen in the nether?  Currently they "attack" the miner and ignore a player. If this changes that behavior, that won't work.
> * [ ]  What will happen if a player tries to teleport on the official servers? Does this prevent that?

1. I stood near the miner. I heard neutral grunts of pig zombies, but did not hear them agri. Broken ores were probably far away. This should be tested, but I do not consider this a critical problem (or I don’t understand why this is a problem). Most players put a miner, a chunkloader, power and leave from there to the base - there is no point in standing and waiting or running around a working miner.
2. Apparently, I have another teleportation plugin, I had no problems with it. I believe that if a miner blocks teleportation, then the problem is in the teleportation plugin, it incorrectly determines whether this player or a fake player. And it should be repaired, this is not a reason to break off the functionality from other parts. Most of the plugins, as I looked, determine the player by his uuid, therefore, casting checks should be done according to him.

**Comment by mitchej123** [comment]
I'm in agreement with (2)

**Comment by GTNH-Colen** [comment]
I can say from first hand experience then whenever the multiblock miner is running you cannot telelport with the plugin, at least on ETA (Official server). If we can fix the plugin that would be amazing I'm just cautious not to add something that will potentially make using the plugin even harder.

Many players have tried reporting this issue before though and gotten no response from staff 
though sadly so I just don't see it getting fixed anytime soon.

**Comment by mitchej123** [comment]
Not fixing something because something else is broken is not the correct approach. 

If the teleport plugin is broken, first find out which one it is, and then find someone to help fix it.

**Comment by GTNH-Colen** [comment]
> Not fixing something because something else is broken is not the correct approach.
> 
> If the teleport plugin is broken, first find out which one it is, and then find someone to help fix it.

Typically I would agree but unfortunately it's not that easy to just get someone who is able to fix issues like this. Obviously I want this fixed but as it seems like we don't have anyone to do it atm adding this would just make the issue worse for no real gains. Not being able to teleport is a much bigger issue than a miner accidentally taking a vein that someone claimed for example.

**Comment by mitchej123** [comment]
Sure it is, ask in #github-discussion or #mod-dev.  Offer up some incentives, monetary or otherwise.  I bet it's a really easy fix to check against `instanceof Fakeplayer`, and since the plugin wouldn't be distributed, it would be fine to decompile, fix, and use it even if it's not open source.  Also it seems there _are_ other plugins that work.

This is a bug in the implementation of the FakePlayer on the base GT -- something that is supported.  The bug you're pointing out is in a Thermos/kCauldron plugin, something that is not supported.  I'm not going to support _not_ fixing a bug in a supported mod to workaround a bug in an unsupported plugin.

**Comment by mitchej123** [comment]
Do you have any evidence this actually makes things worse? Because having looked at it, I don't think it will.

Thermos is not now, nor will it ever, be supported.  (Even for the officials, that's on the admins there)

**Comment by draknyte1** [comment]
> plugins

![B38A9144-4DD8-472D-9690-562E177178D5](https://user-images.githubusercontent.com/3060479/75294452-5e267d80-5820-11ea-8cf0-e0b3e3b458a6.jpeg)

Why there isn’t a forge mod doing the same thing is also puzzling. Still not on us to accommodate Bukkit based rubbish.
