### ISSUE TITLE
Note about Borax (and, probably, some other materials)

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/GT5-Unofficial#28]
@Dream-Master 
If I correctly understand logic of GT materials, material should have bit value 8 in variable ```mTypes``` to have ore block.
But Borax hasn't this bit (it's value = 1) and it is used in GTNH as ore in GT WorldGen config (ore mix 22). If you want to use this material like ore, add bit value 8 to ```mTypes``, i. e. declare material like this:
```
 public static Materials Borax = new Materials( 941, TextureSet.SET_FINE,             1.0F, 0, 1, 1 | 8, 250, 250, 250, 0, "Borax", "Borax", 0, 0, -1, 0, false, false, 1, 1, 1, Dyes.dyeWhite, 1, Arrays.asList(new MaterialStack(Sodium, 2), new MaterialStack(Boron, 4), new MaterialStack(Oxygen, 7), new MaterialStack(Water, 10)));
```

**Comment by Dream-Master** [comment]
Thats true will change it
