### ISSUE TITLE
Cobalt and Reinforced materials seems to have wrong Blast Furnace temperature.

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/GT5-Unofficial#29]
Title says it all. Temperature in Materials class for this materials is 21700 (blast furnace max. temp - 9001).
I guess it's typo. Please fix it (also, check other materials).

**Comment by Dream-Master** [comment]
No it's not. All materials over 20k have custom recipes.  Ask @Technus he coded it.

**Comment by OneEyeMaker** [comment]
But it's unlogical: firstly because of some properties of materials depends on this value, secondly - some addons also can use this field in own purposes.
@Technus  It's better to create separate field to mark some specific materials instead of breaking mod logic: if property was created for storing melting temperature in EBF - this preperty should store only this value and have only this meaning.
But now it has meaning: if value <= 9001 - it's melting temperature in EBF; otherwise - it's another property and has another meaning. 
// *So, why do you need all these properties, if you can store everything in one? ;) *
Summary: I think, that it's bug (problem of architecture) and it should be fixed (for example - by adding field).

**Comment by Technus** [comment]
For our application it works a ok. Might add the field tho to make it more readable.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/7d2b8898c029c98c343ed64cb3150b3b4218684a

**Comment by OneEyeMaker** [comment]
Wow! Very fast, thank you. After finishing moving stuff to work with this field, please change back 20k+ temperatures.

**Comment by Technus** [comment]
it is all done in the commit, unless u talk about me adding new constructor...

**Comment by OneEyeMaker** [comment]
New constructor? Maybe...
This solution is good, but all materials with *proper* values will be available for addons only to ```init``` phase and not on class load (in ```pre-init```). So (IMHO) better to set allproper  temperatures manually and (likely, with new constructor) set this boolean separately.

**Comment by Technus** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/ac015af21a2b2e3e7bb05bd2bda02f8b050396f0

Should do right? @OneEyeMaker

**Comment by Technus** [comment]
to lazy to get new constructor going so added convience method instead

**Comment by OneEyeMaker** [comment]
@Technus 
Good job! Thank you!
