### ISSUE TITLE
Broken recipe ore/oil drilling plant

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT5-Unofficial#297]
gregtech-5.09.33.40 up to v48 ore drilling rig recipe broken and cant craft drilling rig.

**Comment by Dream-Master** [comment]
@Alsarus explain what is broken ?
![image](https://user-images.githubusercontent.com/2970688/83111289-ab86e500-a0c4-11ea-9e62-4c8e95e9da4c.png)
![image](https://user-images.githubusercontent.com/2970688/83111319-b3468980-a0c4-11ea-945a-bd926453cc99.png)
![image](https://user-images.githubusercontent.com/2970688/83111344-ba6d9780-a0c4-11ea-9f44-00a19d753579.png)
![image](https://user-images.githubusercontent.com/2970688/83111359-bf324b80-a0c4-11ea-8266-bf823f66cbb7.png)
![image](https://user-images.githubusercontent.com/2970688/83111404-d40edf00-a0c4-11ea-868e-b17206940708.png)
![image](https://user-images.githubusercontent.com/2970688/83111422-d83afc80-a0c4-11ea-9ab3-6275bcf38f43.png)
![image](https://user-images.githubusercontent.com/2970688/83111428-dbce8380-a0c4-11ea-9a27-4095040767fc.png)

**Comment by Alsarus** [comment]
lol, cant open recipe in inventory. may be i doing something wrong. Here video: https://yadi.sk/i/Jhb73I2YPBBJJQ

**Comment by Dream-Master** [comment]
update to lastest version
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/Client/
