### ISSUE TITLE
Skin not loaded correctly

### ISSUE THREAD

**Issue by zcj924** [GTNewHorizons/GT5-Unofficial#298]
![QQ图片20200528192053](https://user-images.githubusercontent.com/20927006/83135734-df8bf580-a118-11ea-80d1-a9a77dbdd8fd.png)

**Comment by boubou19** [comment]
Can you please provide details about your instance pls?

**Comment by zcj924** [comment]
![2020-05-28 195832](https://user-images.githubusercontent.com/20927006/83138669-b6ba2f00-a11d-11ea-837b-48572edfb421.png)

GregTech.log:  
https://paste.ubuntu.com/p/F6jBbnmvgH/

latest.log  
https://paste.ubuntu.com/p/v3373b2ryK/

What other information do I need to provide

**Comment by GTNH-Afx237v7** [comment]
Modpack Version. Single Player or multiplayer. Official server or private server. Any changes to the pack instance, e.g. Optifine.

**Comment by zcj924** [comment]
Modpack Version 2088
Single Player and multiplayer both be correctly
private server
No changes to the pack
