### ISSUE TITLE
Coil bonus algorithm of EBF doesn't match its description

### ISSUE THREAD

**Issue by Antifluxfield** [GTNewHorizons/GT5-Unofficial#30]
Currently, the high-tier coils always provide a speed bonus ignoring the machine voltage, which means the machine will halve its progress time with a high-tier coil even without any normal overclockness: https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java#L140
That's obviously not an "upgraded overclock" as what its tooltip described.

Is that an intended feature distinct from the original GT?

**Comment by Dream-Master** [comment]
@Antifluxfield 
Maybe i missed some commit. Are you able to do a pull request to fix that?

**Comment by Antifluxfield** [comment]
@Dream-Master Glad to do so. But which one do you prefer: change the algorithm and make it consistent with original GT (and the tooltip), or just correct the tooltip and sustain the current algorithm?

**Comment by Dream-Master** [comment]
@Antifluxfield I mean the speed bonus changing tooltip I can do on my own 😁. Thanks

**Comment by Antifluxfield** [comment]
@Dream-Master  That's it: #31

**Comment by Dream-Master** [comment]
Ok Thanks will Merge later
