### ISSUE TITLE
Deep Dark/ GT5U interaction causing cascading worldgen

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT5-Unofficial#41]
Similar to 
https://github.com/rwtema/extrautilities/issues/1677

When we "fixed" the GT5U code so that it is threadsafe, the DeepDark experiences cascading worldgen and lags the server to death.  

Based on debug, in the Deep Dark chunks are sent twice through chunk generation (at least the GT5U worldgen sees each chunk twice).  When code is added to skip the duplicate chunk generation request, the server still dies.  

This version attempts to thread the chunk generation so that new chunks can be added while processing a chunk.  

ADD WorldGen chunk x:-107 z:-74 SIZE: 902
DUP WorldGen chunk x:-107 z:-74 SIZE: 902 ProcChunks.size(): 902
ADD WorldGen chunk x:-107 z:-73 SIZE: 903
DUP WorldGen chunk x:-107 z:-73 SIZE: 903 ProcChunks.size(): 903
ADD WorldGen chunk x:-107 z:-71 SIZE: 904
DUP WorldGen chunk x:-107 z:-71 SIZE: 904 ProcChunks.size(): 904
ADD WorldGen chunk x:-107 z:-72 SIZE: 905
DUP WorldGen chunk x:-107 z:-72 SIZE: 905 ProcChunks.size(): 905

Here you can see the DUP chunk generation request.  Currently it's thrown away by the GT5U worldgen.  The size() is how large the current pool of pending chunks is.  During normal overworld gen, the pool rarely gets above 50.  With the deep dark, the pool expands until the server runs out of memory or CPU.

Under the old worldgen, chunks were incorrectly thrown away, so the DeepDark worldgen had time to complete. For now, we have reverted to the old worldgen, but would prefer to use the proper worldgen, since discarded chunks don't get *any* GT worldgen, including small ores.

**Comment by richardhendricks** [comment]
Root-caused.  Issue comes from oreveins being potentially larger (max radius=64) than the distance between vein centers (3 chunks or 48). These wide oreveins were causing a cascading worldgen. Setting the max size smaller (31 used in testing) allowed for DeepDark spawn in to complete normally.

**Comment by richardhendricks** [comment]
Replace
                    I:Size_0=64
in worldgenerator.cfg with
                    I:Size_0=32

for all oremixes.

**Comment by Dream-Master** [comment]
Done
