### ISSUE TITLE
Update Seismic Prospector interaction/minigame

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT5-Unofficial#57]
GTNewHorizons/NewHorizons#2223

Make seismic prospector actually kinda useful

Increase area searched to 9x9 chunks. (maybe search just the orevein center chunks?)

Return information on each orevein center in the 9x9 chunks. Maybe mix the info so players still have to at least search the nine locations?

Return information on all the oil in the 9x9 chunks.

Add a low-tier item (lower than datastick) for use in the seismic prospector.  Allow crafting at LV.  Maybe reduce the radius searched?  5x5 would allow checking 4 oreveins if done right.

Fix issue with assembler not distinguising between different books. (may not matter since 9x9 chunks are unlikely to be the same?)

If the bronze-age ore finding device is added, this should be pushed to HV.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2223

**Comment by richardhendricks** [comment]
Also look into bug on assembler - it should not collapse the same pages into one book if the book has zero ores/zero fluids.

**Comment by richardhendricks** [comment]
Still an issue with building it, even at LV - it require certus quartz which is a Nether trip and requires finding a quartz vein.

**Comment by Dream-Master** [comment]
I update Seismic Prospector allready and add new tiers. @richardhendricks look into this issue if you like. Advanced seismic prospector code may be changed. Now it displayed only if a mix is in near/mid or far chunck. Maybe you can add the tool tip be in west/south/north or east.

**Comment by richardhendricks** [comment]
i change the range from the lv to 4 chuncks before it was 5x5 blocks
i add a new tier mv and hv
which have a bigger radius
the adv seismic prospector i change from radius 95 to 120 the max size on us server with 8 chuncks visibility
the only things i like to see here if you scann with the adv seismic prospector the mix is in the west east nort or south direction
now you can see only the mix is near, a bit away and far. This shows your nothing so you can look up any chunck for ores
if you know the ore mix is nears east you can look at near east
or south far you go there and look for it
The whole concept from the seismic prospector is not for practical use
thats why i cahnged waht i can do. I hope you can add the direction to the code from seismic prospector
wall of test and i hope you got what i mean :smiley:

Look at adding information on the chunks tested, ie 
Chunk at 36,36
Vanadium Magnetite
Magnetite
Gold
123L oil

Might do a sample of 5x5 in the center of each chunk instead every block.

**Comment by Dream-Master** [comment]
i think we merge some stuff from main branch allready.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/109 -PR with improvements
