### ISSUE TITLE
GT6 Style pipes Misrouting

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT5-Unofficial#59]
@Antifluxfield

I've been playing with a self compiled version from github and noticed the GT6 style pipes mis-route items when adjacent to a machine/chest.

In the image below, I'd expect the items to route from 1 --> 2 --> 3 (green path).  
However, without any paper between the pipe and 2, the items will route 1 --> 2 --> 2 (red path).  

If I paper the pipe or the chest buffer, it will then route 1 --> 2 --> 1 (pink path)

![pipe misrouting](https://user-images.githubusercontent.com/1894689/33521539-3c1fbebe-d789-11e7-9b40-c7a339f052da.png)

**Comment by Dream-Master** [comment]
@antifluxfield any idea?

**Comment by Antifluxfield** [comment]
Yep, item pipes are missing some logic... I'll find some time to fix it.

**Comment by Dream-Master** [comment]
ok

**Comment by mitchej123** [comment]
The latest prs fix this.
