### ISSUE TITLE
EU P2P channels got broken after the update

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT5-Unofficial#71]
Pack version: 2.0.2.5

Look at the picture:
![image](https://user-images.githubusercontent.com/23512002/34425010-3e23010c-ec39-11e7-80be-102f81b0d1c7.png)

To the right is the input channel, to the left is the output. As soon as I set the left channel to be output (with a memory card), cable disconnects. Wire cutter also does not work.

**Comment by Dream-Master** [comment]
@mitchej123 any idea ?

**Comment by mitchej123** [comment]
Fixed with #73
