### ISSUE TITLE
Large HP turbine does not save 'loose' state upon unload

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT5-Unofficial#72]
saveNBTData() was overridden in GT_MetaTileEntity_LargeTurbine_Steam but not in GT_MetaTileEntity_LargeTurbine_HPSteam

**Comment by Dream-Master** [comment]
@Technus why this was closed

**Comment by repo-alt** [comment]
This is was fixed in #74 why not close it?

**Comment by Dream-Master** [comment]
A ok. @Technus nevermind
