### ISSUE TITLE
Output Hatches don't check connected status of pipes

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT5-Unofficial#81]
Output Hatches don't check connected status of pipes and will happily push fluid into a disconnected pipe in front of the hatch.

**Comment by Antifluxfield** [comment]
Ooops...

**Comment by Technus** [comment]
Fluid pipe solution is total garbage imo.

Lets use this for fluid pipes:
https://github.com/GTNewHorizons/GT5-Unofficial/commit/fcb663754350649e9ce01769f54f850a2c6d262e

**Comment by Technus** [comment]
How to do that on item pipe side, no idea IInventory seems useless...

**Comment by mitchej123** [comment]
Re opening this since the merged fix prevents any non connected pipes from being connected.
