### ISSUE TITLE
High Octane Gasoline Recipe is wrong (doesn't match code)

### ISSUE THREAD

**Issue by codewarrior0** [GTNewHorizons/GT5-Unofficial#97]
Code for High Octane Gasoline [specifies the 5 ingredients](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L3457), but in game only 4 fluid ingredients are used (the AntiKnock fluid Tert-Butyl Ether is missing). This is because [the Large Chemical Reactor is limited to 4 fluid ingredients.](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Recipe.java#L1503)

![image](https://user-images.githubusercontent.com/307683/35206971-50339a88-fee4-11e7-95f6-76732e4f7ef5.png)

**Comment by Dream-Master** [comment]
I ask Johannes Gaessler the creator of the large chemical reactor and he said that 5 fluids work too. Are you tested it? @codewarrior0

**Comment by Dream-Master** [comment]
Will check

**Comment by Dream-Master** [comment]
Maybe add one as cell

**Comment by mitchej123** [comment]
Currently the LCR takes a max of 6 things for a recipe, 2 items 4 liquids -- Any argument against having it take 6 of any combination of fluid/items?
